### Attend Event (Deelname aan evenement)
POST http://localhost:3000/api/EventAttendance/Attend
Content-Type: application/json

{
    "userId": 1,
    "eventId": 1
}

###

### Get Event Attendees (Haal deelnemers van een evenement op)
GET http://localhost:3000/api/EventAttendance/Attendees/1
Accept: application/json

###

### Cancel Attendance (Annuleer deelname aan evenement)
DELETE http://localhost:3000/api/EventAttendance/Cancel
Content-Type: application/json

{
    "userId": 1,
    "eventId": 1
}

###

###
